# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20171210_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要'),
        ),
    ]
