# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20180102_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.Tag', verbose_name='标签'),
        ),
    ]
