# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20180103_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='toc',
            new_name='toc_html',
        ),
    ]
